development:
  # host: localhost
  adapter: postgresql
  encoding: unicode
  database: silostore_development
  pool: 5
  # username: Hugh
  password:

# test:
#   host: localhost
#   adapter: postgresql
#   encoding: unicode
#   database: silostore_test
#   pool: 5
#   username: Hugh
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: silostore_production
#   pool: 5
#   password: